#[program:consumer-pdf]
#command=php /var/www/bin/console messenger:consume async_pdf -vv --time-limit=3600 --memory-limit=256M
#directory=/var/www
#autostart=true
#autorestart=true
#numprocs=1
#stderr_logfile=/var/log/supervisor/consumer-pdf.err.log
#stdout_logfile=/var/log/supervisor/consumer-pdf.out.log
#stopwaitsecs=3600

